---
- name: Setup ntp service
  hosts: all
  roles:
    - role: common-setup
      vars:
        ntp_srv0: 0.in.pool.ntp.org
        ntp_srv1: 1.in.pool.ntp.org
        ntp_srv2: 2.in.pool.ntp.org
        ntp_srv3: 3.in.pool.ntp.org

    - role: geerlingguy.java

