---
# handlers file for common-setup
- name: Restart NTP service on RedHat
  service:
    name: ntpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Restart NTP service on Debian
  service:
    name: ntp
    state: restarted
  when: ansible_os_family == "Debian"

